# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180608_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='date_by',
        ),
        migrations.AddField(
            model_name='order',
            name='date_by',
            field=models.DateField(blank=True, null=True),
        ),
    ]
